export async function generateReport(quizTitle, primaryStyle, data = {}) {
  return `## Your ${quizTitle} DNA
You are a visionary leader who combines strategic thinking with genuine care for your team. Your natural ability to see the bigger picture while maintaining focus on people sets you apart as someone who can lead through both inspiration and authentic connection. You lead with clarity of vision and create environments where others feel safe to contribute their best ideas. Your leadership style is characterized by optimism, curiosity, and a deep commitment to developing the potential in others. You have a unique ability to balance ambitious goals with genuine concern for team wellbeing, making you equally approachable and effective. Your presence tends to elevate team morale and create momentum toward strategic objectives. People describe you as someone who can hold complexity—seeing both the inspiring vision and the practical steps needed to achieve it. You naturally create psychological safety where people feel empowered to take smart risks, experiment, and learn from failures. Your authenticity and transparency build trust quickly, and your genuine interest in others' development creates loyalty that extends beyond typical employment relationships.

## How Others Experience You
- Direct reports consistently describe you as someone who genuinely cares about their success beyond just work performance. They feel heard, valued, and see you as someone who will invest time in their development even when it's not immediately convenient. They appreciate your balance between holding them accountable and supporting them through challenges.
- Peers view you as someone who brings clarity and direction to complex situations while remaining genuinely collaborative. They see you as a connector who builds bridges across functions and brings people together around shared purpose. They appreciate your ability to advocate for your team while also considering broader organizational needs.
- Stakeholders and senior leaders appreciate your ability to balance competing priorities without losing sight of the bigger picture. They recognize your strategic thinking and your capability to translate vision into concrete actions. They see you as someone who delivers on commitments while also building sustainable, engaged teams.
- Your team experiences you as someone who celebrates wins generously but also holds people accountable in a supportive way. They know where they stand with you and feel you have their back. They describe feeling safe to take smart risks and admit mistakes without fear of being punished.
- Clients and external partners see you as credible, forward-thinking, and someone who delivers on commitments. They appreciate your responsiveness and your ability to understand their needs even when not explicitly stated.

## Your 3 Leadership Superpowers
Your first superpower is your ability to see possibilities before others. You naturally envision future states and have a gift for helping others believe in what's possible. You translate abstract vision into compelling narratives that motivate action. You don't just see what could be—you help others see it too and inspire them to work toward it. This forward-looking perspective helps you anticipate market changes, organizational needs, and talent development opportunities before they become obvious to others. Your teams benefit from your optimism and possibility-focused thinking, especially during uncertain times.

Your second strength is your emotional intelligence and relational capability. You read the room instinctively, adjust your approach based on emotional cues, and build genuine connections quickly. You understand that leadership is fundamentally about people, and you invest accordingly. Your ability to listen deeply, ask powerful questions, and see people's potential creates an environment where people want to do their best work. You naturally mentor others and create development opportunities. People feel valued in your presence, not just for what they do but for who they are.

Your third superpower is your decisiveness combined with inclusivity. You can make tough calls when needed while ensuring people feel heard and valued in the process. You don't get paralyzed by needing everyone to agree before moving forward, yet you also don't make decisions in isolation. You find the balance between gathering input and moving with conviction. This combination allows you to lead decisively through change while maintaining trust and engagement with your team.

## Your Growth Edge & Derailers
When stressed or under pressure, you can become overly focused on details and operational issues, losing sight of the bigger strategic picture that is your natural strength. You may micromanage or get pulled into execution when you should be focused on direction-setting. Recognizing when stress is causing you to contract and consciously returning to your big-picture perspective will help you maintain your effectiveness during challenging periods.

Your tendency to want consensus and buy-in from others can sometimes slow decision-making when speed is critical. You may spend too much time building alignment when the organization needs you to move faster. Learning to read situations more accurately and knowing when to move forward with imperfect alignment will accelerate your impact. Some people may experience your consensus-seeking as indecision or lack of conviction.

You may sometimes over-communicate your vision without ensuring clarity on execution. Your teams may understand where you want to go but be unclear about how to get there or what their specific role is. Being more explicit about next steps and clarifying roles and responsibilities will improve execution. You might assume others understand your vision when they actually need more concrete guidance.

Your high expectations for yourself can sometimes translate into pressure others feel from you. You may not realize how much your team looks to you for direction and see your questions or concerns as directive even when you intend them as exploratory. Being more aware of your power and influence will help you lead with greater ease.

## Communication & Influence Style
You communicate best through dialogue, storytelling, and genuine connection. You excel at translating abstract concepts into compelling narratives that help people understand not just the what but the why. You prefer building consensus and create genuine space for others' perspectives before deciding. Your influence comes from your authenticity—people can tell you actually believe what you're saying and care about the outcomes. You build genuine relationships that become the foundation for influence. Your preferred channels are one-on-one conversations and small group discussions where deeper dialogue and connection can occur. You're less comfortable with formal presentations to large audiences unless you have time to build connection with the group.

You tend to lead through questions and curiosity rather than directives. You help people think through problems rather than telling them what to do. This approach develops capability in others but can sometimes feel slow to people who prefer more direct guidance. You naturally build coalitions and partnerships rather than relying on formal authority to get things done. You're genuinely interested in understanding different perspectives and often find creative solutions that incorporate multiple viewpoints.

## Team Dynamics & Impact
Your team thrives in environments where they feel heard, valued, and have clarity on direction. You create psychological safety that allows people to take smart risks, admit mistakes, and experiment. Your collaborative approach builds deep loyalty and commitment—people don't just work for you because it's their job but because they believe in you and feel invested in mutual success. You tend to empower others effectively and delegate in ways that develop capability. Your focus on development means your team members often advance to bigger roles, and you take pride in their growth. Team members describe you as someone who genuinely cares about their success beyond just work performance. Your teams tend to be engaged, innovative, and willing to go the extra mile.

However, your team can sometimes lack clarity on your priorities or next steps. They may need more explicit communication about what success looks like and how you'll measure progress. They might also experience some tension between your vision-focused, big-picture thinking and the need for operational clarity and execution. Some team members may feel they need more direction from you, especially if they're early in their careers or prefer more structured guidance.

## Leadership Blind Spots
You may underestimate how much your team looks to you for direction and clear decision-making. Your questions or exploratory comments might be experienced as directive by people who are looking for your conviction. You may not realize the power of your position and how much weight your words carry with your team.

You sometimes assume others understand your vision when they actually need more explicit clarity about execution. What's crystal clear in your mind may be ambiguous to others. Your team might understand the destination but be unclear about the path or their specific role.

Your high expectations for yourself can sometimes translate as pressure others feel from you, even when you don't intend it that way. You may have blind spots about how demanding or perfectionist you come across. Taking time to appreciate progress and celebrate small wins more explicitly will help offset this perception.

You may be too quick to validate others' concerns, which can sometimes create indecision or send mixed messages about your conviction. People might not know if you truly support a direction or if you're just being supportive of their concerns. Being clearer and more decisive about your actual position will strengthen your leadership.

## Your 30-Day Action Plan
Week 1 - Build Self-Awareness: Schedule and conduct 1-on-1 feedback conversations with your 5 key stakeholders: two direct reports, two peers, and your boss. Ask these questions: "What's one thing I do well that I should keep doing?" "What's one area where I could be more effective?" "How do I show up when things are stressful?" "What do you need from me as a leader?" Listen without defending. Take detailed notes on themes. What patterns emerge? What surprises you? Schedule a 90-minute reflection meeting with your executive coach or trusted mentor to process the feedback and identify themes.

Week 2 - Clarify Your Leadership: Complete a self-reflection exercise. Write down your top 3 leadership strengths based on feedback and your own experience. For each strength, identify 2-3 specific recent examples where you demonstrated it and the impact. Then identify your top 2-3 development areas. For each, describe one situation where this showed up and what you wish you'd handled differently. What patterns do you see in your development areas? When do they show up most? Share your reflection with your executive coach and ask for perspective on whether these are accurate and actionable.

Week 3 - Create Your Vision and Priorities: Create a one-page leadership vision and priorities document. Articulate: (1) Your leadership aspiration—what do you want to be known for in 2 years? What impact do you want to have? (2) Your top 3 priorities for the next 90 days, connected to your development. How will addressing these development areas make you a more effective leader? (3) How you'll measure success—what will be different 90 days from now? What specific behaviors will change? What results will you see? Share this with your boss and top 3 stakeholders to ensure alignment and commitment.

Week 4 - Launch Your Practice: Identify 2-3 small, specific micro-habits you'll practice daily or weekly aligned with your development. Examples: "Have 3 genuine one-on-ones focused on listening before offering advice," "Send one message recognizing someone's specific contribution," "Make one decision without seeking consensus and explain my thinking," "Ask three powerful questions before offering solutions." Schedule weekly 30-minute "reflection" blocks to track progress. What worked? What was hard? What will you adjust next week? Who will hold you accountable to these practices?`;
}
